### ISSUE TITLE
No Integration to HomeKit with Homebridge v1.6.1

### ISSUE THREAD

**Issue by J1K-Hub** [schroedan/homebridge-my-gekko#22]
The plugin can be integrated into Homebridge v1.6.1 and you can see all devices in Homebridge.
As soon as you want to integrate the bridge into Homekit, the error "Device cannot be added. Device is not compatible" ("Gerät kann nicht hinzugefügt werden. Gerät ist nicht kompatibel"). 

With the Homebridge v1.4.1 everything runs stable.

**Comment by schroedan** [comment]
I have finally managed to provide a new version 0.3.0 of the plugin, which is compatible with the current versions of Homebridge.
